sss<?php 
$oForm = new Form('post', '', array ('ss'=>'ss')); 
$oForm->openForm();
$oForm->addInput(
	'text', 
	'name', 
	'', 
	array ( 'class' => 'customText', 'style' => '1px solid red'),
    TRUE,
    array (
    	array ('type' => 'required', 'errorMessage' => 'Campul acesta nu trebuie sa fie gol'),
    	array ('type' => 'email')
	)
);
$oForm->closeForm();
?>
ss
<p>Static paragrapth</p>
<p>var1 = <?php echo $var1; ?></p>
<p>var2 = <?php echo $var2; ?></p>
